### ISSUE TITLE
Overview issue

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-cli#1]
Originally [here](https://github.com/fpco/stackage/issues/396#issuecomment-84972291). Here is a list of steps to get this off the ground:
- [x] `Stackage.CLI` library #2
- [x] `stackage` executable #3
- [x] `stackage-init` executable #4
- [x] `stackage-purge` executable #5
- [x] `stackage-upgrade` executable #6

There should be Haddock documentation for the exposed exports in `Stackage.CLI`, for us and because this will be a public project eventually.
